### ISSUE TITLE
Problem with DUs with a case of array type

### ISSUE THREAD

**Issue by bratfizyk** [15below/FifteenBelow.Json#12]
I use the library together with Json.NET.

I found a problem while deserializing a specific type of DU. Here's an example:

```F#
type MyDU = MyCase of int[]
```

so a DU with a case that has exactly one field, which is an array

For example "MyCase [| 1; 2; 3 |]" gets serialized as: 
```JSON
{
  "MyCase": [
    [
      1,
      2,
      3
    ]
  ]
}
```
However, when attempting to deserialize this, I get an exception:
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value 1 to type 'System.Int[]'. Path 'MyCaseTest[0][0]', line 4, position 8. ---> System.ArgumentException: Could not cast or convert from System.Int to System.Int[].

I believe that's because the function "readArray" consumes all the leading '[' characters, making it impossible for Json.NET to convert "1,2,3]" into an int[]. 

A naive solution would be to make sure a '[' character is consumed exactly once, but I'm not that fluent with using computation expressions, so maybe there's a better solution that I simply can't see.

**Comment by kjnilsson** [comment]
Hi - thanks for the bug report. We'll take a look at it.

**Comment by kjnilsson** [comment]
Hello - apologies for being slow responding to this. I added a test for your scenario and it passes fine./ Could you be using and older version than the latest one?

Check this test in my fork and see if I am doing anything differently from you.

https://github.com/kjnilsson/FifteenBelow.Json/blob/master/src/FifteenBelow.Json.Tests/Tests.fs#L28

**Comment by kjnilsson** [comment]
Ah it appears the converter aren't running so defaulted to standard json.net serialization. not sure why that is happening. Will continue investigations.

**Comment by kjnilsson** [comment]
ok this should be fixed now. @bratfizyk - if you have an opportunity to test it please do so and reopen this issue if it does not work for you. Cheers.

**Comment by bratfizyk** [comment]
OK - thanks. I'll take a look and let you know.

**Comment by bratfizyk** [comment]
Looks nice - thank you for solving the problem!
